name: Build LaTeX document
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
#####################################################################
      - name: Set up Git repository
        uses: actions/checkout@v2
#####################################################################
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
#          working_directory: report/
          root_file: main.tex
      - name: Rename PDF file
        run: |
          mv main.pdf math-proba.pdf
#####################################################################
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            math-proba.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}